export const PROJECT_STATUS = {
  COMPLETED: 'COMPLETED',
  ONGOING: 'ONGOING',
  NOT_STARTED: 'NOT_STARTED',
  DELAYED: 'DELAYED',
};

export const PROJECT_STATUS_LABELS = {
  [PROJECT_STATUS.COMPLETED]: 'Completed',
  [PROJECT_STATUS.ONGOING]: 'Ongoing',
  [PROJECT_STATUS.NOT_STARTED]: 'Not Started',
  [PROJECT_STATUS.DELAYED]: 'Delayed',
};

export const PROJECT_STATUS_COLORS = {
  [PROJECT_STATUS.COMPLETED]: 'emerald',
  [PROJECT_STATUS.ONGOING]: 'indigo',
  [PROJECT_STATUS.NOT_STARTED]: 'amber',
  [PROJECT_STATUS.DELAYED]: 'rose',
};
